### ISSUE TITLE
Help with flashing device

### ISSUE THREAD

**Issue by sebska** [haemka/OpenBK7231-Antela-F1s203-EU#1]
Hi,

i wanted to use your descripion, but i am stuck at "At this point you can flash as usual using [OpenBK7231T_App](https://github.com/openshwprojects/OpenBK7231T_App). For me this worked best through Windows (VM). Flashing with the App through Linux failed repeatedly."

I am using Win11 but i have touble creating a Flashtool...

Can you help me please?

Best Wishes Sebastian from Germany

**Comment by openshwprojects** [comment]
You dont need to build frm scratch, we have premade binaries.
Have you seen our tutorials:
https://www.youtube.com/@elektrodacom

**Comment by sebska** [comment]
https://github.com/openshwprojects/OpenBK7231T_App/issues/1006
